export const Action_type = {
    SERVICES_REQ: "SERVICES_REQ",
    SERVICES_SHOW: "SERVICES_SHOW",
    SERVICES_FAIL: "SERVICES_FAIL",
    // -- cart data--
    CARTDATAREQ: "CARTDATAREQ",
    CARTDATA: "CARTDATA",
    CARTDATAFAIL: "CARTDATAFAIL",
    // --add to cart--
    ADDTOCART: "ADDTOCART",
    // -- product detials--
    PRODUCTDETIALS_REQ: "PRODUCTDETIALS_REQ",
    PRODUCTDETIALS_SUCCESS: "PRODUCTDETIALS_SUCCESS",
    PRODUCTDETIALS_FAIL: "PRODUCTDETIALS_FAIL",
    // -- product detials remove--
    PRODUCTDETIALS_REMOVE: "PRODUCTDETIALS_REMOVE",

}